### PR TITLE
fix #13: Add footerBuilder to keyboardAction

### LINKED ISSUE #13: improvement: support custom footer widget
Hey, so my most recent project has been to add a custom keyboard :) Thought I would open an issue to track if we wanted to support it here. I've been working on a change to allow a KeyboardAction to specify a custom overlay widget. 

 The widget would be shown below below the keyboard action bar. My use case is to implement a custom keyboard, for inputs that don't use the system keyboard, e.g. a color input:

custom_keyboard

It could also be used along with the system keyboard for things like providing some instructions, an error message, or input suggestions.

### PR DESCRIPTION
**Pull request by jaysephjw**
Let each keyboard action have a custom footer widget, like this: 
```
 KeyboardAction(
          focusNode: _nodeText6,
          footerBuilder: (_) => PreferredSize(
              child: SizedBox(height: 40, child: Center(child: Text('Custom Footer'),)),
              preferredSize: Size.fromHeight(40)),
        ),
```
Screen Shot 2019-05-22 at 5 46 50 PM

For more fun, use that widget as a custom keyboard with your custom input:

Screen Shot 2019-05-22 at 5 46 54 PM

* Wrap a BottomAreaAvoider instead of KeyboardAvoider so we can have better control over how the content resizes. 
* Resize the BottomAreaAvoider based on the bar height, system keyboard height, and footer height.
* update example with example custom inputs

### CODE REVIEW

**Comment by diegoveloper** [comment]
Hi @jaysephjw , I have some issues using your repo : 

1-  SDK version >=2.3.0 <3.0.0, version solving failed.
I'm using dev channel this version :

```
Flutter 1.5.8 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 0ba67226ee (4 weeks ago) • 2019-04-24 17:18:28 -0700
Engine • revision c63d1cf9c9
Tools • Dart 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)
```
And you ?

2- In `custom_input.dart` this class/method are not recognized:  `Focus` and `widget.focusNode.requestFocus();`

**Comment by jaysephjw** [comment]
I was using master @ `[✓] Flutter (Channel master, v1.6.1-pre.34, on Mac OS X 10.14.4 18E226, locale en-US)`. Let me switch to dev and try it out!

**Comment by jaysephjw** [comment]
Works for me with 
```
[✓] Flutter (Channel dev, v1.6.1, on Mac OS X 10.14.4 18E226, locale en-US)
```
try flutter upgrade to get the latest dev maybe.

hmm Focus should come in with `import 'package:flutter/material.dart'`. Maybe newer flutter engine will clear it up.

**Comment by diegoveloper** [comment]
Ok, now it's working , just some issues: 

- remove buildAnimatedContainer w  log
- when I select the textfield with the custom input I get these error log: 

```
flutter: buildAnimatedContainer w 245.0
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/rendering/box.dart': Failed assertion: line 2156 pos 12: 'child.parent ==
flutter: this': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderBox.applyPaintTransform 
package:flutter/…/rendering/box.dart:2156
flutter: #3      _RenderDecoration.applyPaintTransform 
package:flutter/…/material/input_decorator.dart:1360
flutter: #4      _SemanticsGeometry._transformRect 
package:flutter/…/rendering/object.dart:3579
flutter: #5      _SemanticsGeometry._computeValues 
package:flutter/…/rendering/object.dart:3557
flutter: #6      new _SemanticsGeometry 
package:flutter/…/rendering/object.dart:3521
flutter: #7      _SwitchableSemanticsFragment.compileChildren 
package:flutter/…/rendering/object.dart:3390
flutter: #8      _SyncIterator.moveNext  (dart:core-patch/core_patch.dart:152:12)
flutter: #9      List.addAll  (dart:core-patch/growable_array.dart:193:13)
flutter: #10     _SwitchableSemanticsFragment.compileChildren 
package:flutter/…/rendering/object.dart:3422
flutter: #11     _SyncIterator.moveNext  (dart:core-patch/core_patch.dart:152:12)
flutter: #12     List.addAll  (dart:core-patch/growable_array.dart:193:13)
flutter: #13     _SwitchableSemanticsFragment.compileChildren 
package:flutter/…/rendering/object.dart:3422
flutter: #14     _SyncIterator.moveNext  (dart:core-patch/core_patch.dart:152:12)
flutter: #15     List.addAll  (dart:core-patch/growable_array.dart:193:13)
flutter: #16     _SwitchableSemanticsFragment.compileChildren 
package:flutter/…/rendering/object.dart:3422
flutter: #17     _SyncIterator.moveNext  (dart:core-patch/core_patch.dart:152:12)

```

**Comment by jaysephjw** [comment]
Cool. For the error, I actually created a bug on the main flutter repo.

I'm AFK today but will update tomorrow 👍

**Comment by diegoveloper** [comment]
@jaysephjw Would be great if you could update the `README.md` file with the gifs files you have. 
Thanks for your awesome work!

**Comment by jaysephjw** [comment]
ok, updated 👍

**Comment by diegoveloper** [comment]
Thanks again! @jaysephjw  great job man!

**Comment by diegoveloper** [comment]
Hey @jaysephjw I've just updated the package with some changes (because the analysis was in red).
https://pub.dev/packages/keyboard_actions/versions/2.1.0#-analysis-tab-

**Comment by jaysephjw** [comment]
@diegoveloper awesome, thanks 👍 Good idea to just add BottomAreaAvoider and remove the dependency.

I don't think KeyboardAvoider is used (FormKeyboardActions just uses BottomAreaAvoider) so we can probably remove that class.

**Pull request merged**
