### PR TITLE
fix: open custom keyboard after default keyboard

### PR DESCRIPTION
**Pull request by Arenukvern**
@diegoveloper This PR can help with #173 problem.

Will be glad for your opinion and review!

### CODE REVIEW

**Comment by diegoveloper** [comment]
Hello , did you check this doesn't break any other behavior? I'll try it later

**Comment by Arenukvern** [comment]
> Hello , did you check this doesn't break any other behavior? I'll try it later

Checked only the switches between keyboards, close and open default and custom keyboards,  focus changes buttons (arrows).

**Comment by diegoveloper** [comment]
hey @Arenukvern I couldn't reproduce the issue on iOS, so maybe this is an android only issue.


https://user-images.githubusercontent.com/4898256/147397633-3db6f9cf-2ead-4723-9d40-d5707ed99944.mov

Can you add a validation only for Android? 

```dart
if ( PlatformCheck.isAndroid &&  ( value > 0 || _currentAction?.focusNode.hasFocus) ) 

```

**Comment by Arenukvern** [comment]
> hey @Arenukvern I couldn't reproduce the issue on iOS, so maybe this is an android only issue.
> 
>  Screen.Recording.2021-12-25.at.9.41.13.PM.mov 
> 
> Can you add a validation only for Android?
> 
> ```dart
> if ( PlatformCheck.isAndroid &&  ( value > 0 || _currentAction?.focusNode.hasFocus) ) 
> ```
Hi @diegoveloper,

Yes, you are right, it seems like Android only issue.
Made a fix, could you please take a look?

**Comment by diegoveloper** [comment]
Hey, I'll check it tomorrow, thanks

**Comment by diegoveloper** [comment]
Thanks, great job @Arenukvern

**Pull request merged**
