### PR TITLE
Add option to specify a default "Done" widget in the config

### LINKED ISSUE #159: Support setting a default `doneButton` widget
Currently, the only way to modify the looks of the "Done" button, is to set it for each `KeyboardActionsItem`.
This can be inflexible when working with bigger forms with a need to set the content of the "Done" button from a widget that is higher in the widget tree than the fields with the `FocusNode`s controlled by top `KeyboardActions` widget.

It would be nice to be able to **optionally** set a default `Widget` to be used instead of the hard-coded "Done" button.

### PR DESCRIPTION
**Pull request by peter-gy**
Minimalistic way to let users specify a custom Widget instead of the default "Done" widget to be used.

Closes #159

### CODE REVIEW

**Comment by diegoveloper** [comment]
hey, this change looks good. thanks @peter-gy , just one thing, can you add a new sample (inside the project), using this new widget?

**Comment by peter-gy** [comment]
> hey, this change looks good. thanks @peter-gy , just one thing, can you add a new sample (inside the project), using this new widget?

Hey @diegoveloper!

Yes, gladly!

**Comment by peter-gy** [comment]
@diegoveloper ,
I added a minimal example as `sample3.dart` that shows how to leverage `KeyboardActionsConfig.defaultDoneWidget`.

**Comment by diegoveloper** [comment]
thank you :D

**Pull request merged**
