### PR TITLE
add customer widget to keybaordaction

### PR DESCRIPTION
**Pull request by disburden**
as title

### CODE REVIEW

**Comment by diegoveloper** [comment]
@jaysephjw what do you think about this PR? any suggestion?

**Comment by jaysephjw** [comment]
Seems like this would be a nice feature if you think so too (to totally replace the custom keyboard bar).  However I'm working on #13 which will also add a custom child, just below the existing bar.

So I say maybe hold off on merging this for now? I can look for a solution that will support both (entirely custom bar, and custom view beneath existing bar).

**Comment by jaysephjw** [comment]
re this pr specifically, one thing to address is there's no promise this custom bar matches _kBarHeight, so the scrolling logic could be off.

Also quick question @disburden, wouldn't you want the custom bar for the whole KeyboardActionsConfig, not just a single KeyboardAction?

**Comment by disburden** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you for your reply!
        I just happened to have this requirement, so I made modifications by myself. The purpose of submitting this pr is hope you provider similar functions, and I didn't design it carefully, so it's up to you
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                disburden
                            
                    
                        
                            
                                    disburden@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 05/22/2019 02:12，Jay<notifications@github.com> wrote： 


re this pr specifically, one thing to address is there's no promise this custom bar matches _kBarHeight, so the scrolling logic could be off.
Also quick question @disburden, wouldn't you want the custom bar for the whole KeyboardActionsConfig, not just a single KeyboardAction?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jaysephjw** [comment]
Ok I created https://github.com/diegoveloper/flutter_keyboard_actions/issues/18 to track this request. I think this PR can be closed as there is probably a cleaner way to do it.

**Pull request closed without merging**
